version: '3'
services:
  employeemanager:
    container_name: employeemanager
    build:
      context: .
      dockerfile: dockerfile_employeemanager
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=whoami.local

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    depends_on:
      - employeemanager

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.0.0/16
